export const REGIONS = [
  { value: "tarapaca", label: "Tarapacá" },
  { value: "antofagasta", label: "Antofagasta" },
  { value: "atacama", label: "Atacama" },
  { value: "coquimbo", label: "Coquimbo" },
  { value: "valparaiso", label: "Valparaíso" },
  { value: "ohiggins", label: "O'Higgins" },
  { value: "maule", label: "Maule" },
  { value: "biobio", label: "Biobío" },
  { value: "araucania", label: "Araucanía" },
  { value: "los_rios", label: "Los Ríos" },
  { value: "los_lagos", label: "Los Lagos" },
  { value: "aysen", label: "Aysén" },
  { value: "magallanes", label: "Magallanes" },
  { value: "rm", label: "Metropolitana" },
  { value: "arica", label: "Arica y Parinacota" },
  { value: "nuble", label: "Ñuble" },
];

export const COMMUNES: Record<string, string[]> = {
  tarapaca: ["Iquique", "Alto Hospicio", "Pica", "Pozo Almonte", "Huara", "Camiña", "Colchane"],
  antofagasta: ["Antofagasta", "Mejillones", "Sierra Gorda", "Taltal", "Calama", "Ollagüe", "San Pedro de Atacama", "Tocopilla", "María Elena"],
  atacama: ["Copiapó", "Caldera", "Tierra Amarilla", "Chañaral", "Diego de Almagro", "Vallenar", "Huasco", "Freirina", "Alto del Carmen"],
  coquimbo: ["La Serena", "Coquimbo", "Andacollo", "Vicuña", "Paihuano", "Ovalle", "Monte Patria", "Combarbalá", "Río Hurtado", "Illapel", "Salamanca", "Los Vilos", "Canela", "Punitaqui"],
  valparaiso: ["Valparaíso", "Viña del Mar", "Concón", "Quintero", "Puchuncaví", "Quilpué", "Villa Alemana", "Limache", "Olmué", "San Antonio", "Cartagena", "El Tabo", "San Pedro", "Santo Domingo", "Los Andes", "San Felipe", "La Ligua", "Cabildo", "Zapallar", "Petorca", "Papudo", "Isla de Pascua"],
  ohiggins: ["Rancagua", "Graneros", "San Fernando", "Santa Cruz", "Pichilemu", "San Vicente de Tagua Tagua", "Rengo", "Doñihue", "Coltauco", "Codegua", "Machalí", "Olivar", "Malloa", "Placilla", "Nancagua", "Palmilla", "Lolol", "Chépica", "Peralillo"],
  maule: ["Talca", "Curicó", "Linares", "Constitución", "San Clemente", "Pelarco", "Río Claro", "Maule", "San Javier", "Villa Alegre", "Yerbas Buenas", "Colbún", "Longaví", "Parral", "Retiro", "Cauquenes", "Chanco", "Empedrado", "Licantén", "Molina", "Hualañé", "Curanipe", "Sagrada Familia"],
  biobio: ["Concepción", "Talcahuano", "San Pedro", "Chiguayante", "Hualpén", "Penco", "Tomé", "Coronel", "Lota", "San Rosendo", "Hualqui", "Santa Juana", "Cañete", "Arauco", "Lebu", "Los Álamos", "Curanilahue", "Los Ángeles", "Mulchén", "Nacimiento", "Yumbel", "Cabrero", "Laja", "San Rosendo", "Quilleco", "Tucapel", "Antuco", "Alto Biobío"],
  araucania: ["Temuco", "Padre Las Casas", "Villarrica", "Pucón", "Freire", "Pitrufquén", "Gorbea", "Toltén", "Saavedra", "Teodoro Schmidt", "Los Sauces", "Lautaro", "Perquenco", "Victoria", "Traiguén", "Lumaco", "Ercilla", "Collipulli", "Angol", "Renaico", "Curacautín", "Lonquimay", "Melipeuco", "Cunco", "Puerto Saavedra"],
  los_rios: ["Valdivia", "Corral", "Mariquina", "Lanco", "Los Lagos", "Máfil", "Paillaco", "Panguipulli", "La Unión", "Futrono", "Río Bueno", "Lago Ranco"],
  los_lagos: ["Puerto Montt", "Calbuco", "Maullín", "Los Muermos", "Llanquihue", "Frutillar", "Puerto Varas", "Freshwater", "Osorno", "San Pablo", "Río Negro", "Purranque", "Puerto Octay", "Ancud", "Castro", "Quellón", "Dalcahue", "Chaitén", "Hualaihué", "Futaleufú", "Palena", "Cochamó"],
  aysen: ["Coyhaique", "Puerto Aysén", "Chile Chico", "Cisnes", "Río Ibáñez", "Puerto Cisnes", "Tortel", "O'Higgins", "Lago Verde", "Guaitecas"],
  magallanes: ["Punta Arenas", "Puerto Natales", "Porvenir", "Cabo de Hornos", "Torres del Payne", "Laguna Blanca", "Río Verde", "San Gregorio", "Primavera", "Timaukel"],
  rm: ["Santiago", "Providencia", "Las Condes", "Vitacura", "Lo Barnechea", "Ñuñoa", "La Reina", "Peñalolén", "Macul", "San Joaquín", "La Florida", "Puente Alto", "La Granja", "El Bosque", "San Ramón", "San Miguel", "La Cisterna", "Pedro Aguirre Cerda", "Lo Espejo", "Cerrillos", "Maipú", "Estación Central", "Cerro Navia", "Lo Prado", "Pudahuel", "Quinta Normal", "Recoleta", "Independencia", "Renca", "Conchalí", "Huechuraba", "Quilicura", "Colina", "Lampa", "San Bernardo", "Buin", "Paine", "Peñaflor", "Melipilla", "Curacaví", "Talagante", "Isla de Maipo", "Padre Hurtado", "San José de Maipo", "Pirque", "Calera de Tango"],
  arica: ["Arica", "Camarones", "Putre", "General Lagos"],
  nuble: ["Chillán", "Chillán Viejo", "San Carlos", "Quirihue", "Coelemu", "Trehuaco", "Cobquecura", "Coihueco", "San Fabián", "San Ignacio", "El Carmen", "Pemuco", "Yungay", "Ránquil", "Portezuelo", "Ninhue", "Parral"],
};