-- PiwiSuite Vet - Species Groups & Breeds
-- Adds structured species/breed catalog to D1

CREATE TABLE IF NOT EXISTS species_groups (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS breeds (
  id TEXT PRIMARY KEY,
  species_group_id TEXT NOT NULL REFERENCES species_groups(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  breed_group TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(species_group_id, name)
);

CREATE INDEX IF NOT EXISTS idx_breeds_species ON breeds(species_group_id);
CREATE INDEX IF NOT EXISTS idx_breeds_name ON breeds(name);

-- Species groups
INSERT OR IGNORE INTO species_groups (id, name, display_order) VALUES
  ('species-perro', 'Perro', 1),
  ('species-gato', 'Gato', 2),
  ('species-ave', 'Ave', 3),
  ('species-exotico', 'Animal Exótico', 4),
  ('species-granja', 'Animal de Granja', 5),
  ('species-reptil', 'Reptil', 6),
  ('species-roedor', 'Roedor', 7),
  ('species-conejo', 'Conejo y Lagomorfos', 8),
  ('species-huron', 'Hurón', 9),
  ('species-equino', 'Equino', 10),
  ('species-otro', 'Otro', 11);

-- Perros (reutilizando catálogo existente)
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-perro-mestizo', 'species-perro', 'Mestizo', 'Mestizos y comunes'),
  ('breed-perro-quiltro', 'species-perro', 'Quiltro', 'Mestizos y comunes'),
  ('breed-perro-srd', 'species-perro', 'Sin raza definida (SRD)', 'Mestizos y comunes'),
  ('breed-perro-cruza-pequena', 'species-perro', 'Cruza pequeña', 'Mestizos y comunes'),
  ('breed-perro-cruza-mediana', 'species-perro', 'Cruza mediana', 'Mestizos y comunes'),
  ('breed-perro-cruza-grande', 'species-perro', 'Cruza grande', 'Mestizos y comunes'),
  ('breed-perro-cruza', 'species-perro', 'Cruza', 'Mestizos y comunes'),
  ('breed-perro-en-evaluacion', 'species-perro', 'En evaluación', 'Mestizos y comunes'),
  ('breed-perro-no-identificada', 'species-perro', 'No identificada', 'Mestizos y comunes'),
  ('breed-perro-otra', 'species-perro', 'Otra raza', 'Mestizos y comunes'),
  ('breed-perro-chihuahua', 'species-perro', 'Chihuahua', 'Razas pequeñas'),
  ('breed-perro-yorkshire', 'species-perro', 'Yorkshire Terrier', 'Razas pequeñas'),
  ('breed-perro-pomerania', 'species-perro', 'Pomerania', 'Razas pequeñas'),
  ('breed-perro-maltes', 'species-perro', 'Maltés', 'Razas pequeñas'),
  ('breed-perro-shih-tzu', 'species-perro', 'Shih Tzu', 'Razas pequeñas'),
  ('breed-perro-pug', 'species-perro', 'Pug', 'Razas pequeñas'),
  ('breed-perro-pequines', 'species-perro', 'Pekinés', 'Razas pequeñas'),
  ('breed-perro-pinscher-mini', 'species-perro', 'Pinscher Miniatura', 'Razas pequeñas'),
  ('breed-perro-fox-terrier-toy', 'species-perro', 'Fox Terrier Toy', 'Razas pequeñas'),
  ('breed-perro-bichon-frise', 'species-perro', 'Bichón Frisé', 'Razas pequeñas'),
  ('breed-perro-bichon-maltes', 'species-perro', 'Bichón Maltés', 'Razas pequeñas'),
  ('breed-perro-boston-terrier', 'species-perro', 'Boston Terrier', 'Razas pequeñas'),
  ('breed-perro-jack-russell', 'species-perro', 'Jack Russell Terrier', 'Razas pequeñas'),
  ('breed-perro-schnauzer-mini', 'species-perro', 'Schnauzer Miniatura', 'Razas pequeñas'),
  ('breed-perro-caniche-toy', 'species-perro', 'Caniche Toy', 'Razas pequeñas'),
  ('breed-perro-caniche-mini', 'species-perro', 'Caniche Mini', 'Razas pequeñas'),
  ('breed-perro-dachshund', 'species-perro', 'Dachshund / Salchicha', 'Razas pequeñas'),
  ('breed-perro-bulldog-frances', 'species-perro', 'Bulldog Francés', 'Razas pequeñas'),
  ('breed-perro-cavalier', 'species-perro', 'Cavalier King Charles Spaniel', 'Razas pequeñas'),
  ('breed-perro-papillon', 'species-perro', 'Papillón', 'Razas pequeñas'),
  ('breed-perro-coton-tulear', 'species-perro', 'Coton de Tuléar', 'Razas pequeñas'),
  ('breed-perro-west-highland', 'species-perro', 'West Highland White Terrier', 'Razas pequeñas'),
  ('breed-perro-lhasa-apso', 'species-perro', 'Lhasa Apso', 'Razas pequeñas'),
  ('breed-perro-beagle', 'species-perro', 'Beagle', 'Razas medianas'),
  ('breed-perro-border-collie', 'species-perro', 'Border Collie', 'Razas medianas'),
  ('breed-perro-cocker-ingles', 'species-perro', 'Cocker Spaniel Inglés', 'Razas medianas'),
  ('breed-perro-cocker-americano', 'species-perro', 'Cocker Spaniel Americano', 'Razas medianas'),
  ('breed-perro-bulldog-ingles', 'species-perro', 'Bulldog Inglés', 'Razas medianas'),
  ('breed-perro-bull-terrier', 'species-perro', 'Bull Terrier', 'Razas medianas'),
  ('breed-perro-staffordshire-bull', 'species-perro', 'Staffordshire Bull Terrier', 'Razas medianas'),
  ('breed-perro-schnauzer-estandar', 'species-perro', 'Schnauzer Estándar', 'Razas medianas'),
  ('breed-perro-samoyedo', 'species-perro', 'Samoyedo', 'Razas medianas'),
  ('breed-perro-shar-pei', 'species-perro', 'Shar Pei', 'Razas medianas'),
  ('breed-perro-whippet', 'species-perro', 'Whippet', 'Razas medianas'),
  ('breed-perro-setter-ingles', 'species-perro', 'Setter Inglés', 'Razas medianas'),
  ('breed-perro-springer', 'species-perro', 'Springer Spaniel', 'Razas medianas'),
  ('breed-perro-husky', 'species-perro', 'Husky Siberiano', 'Razas medianas'),
  ('breed-perro-aussie-shepherd', 'species-perro', 'Australian Shepherd', 'Razas medianas'),
  ('breed-perro-pastor-australiano', 'species-perro', 'Pastor Australiano', 'Razas medianas'),
  ('breed-perro-kelpie', 'species-perro', 'Kelpie Australiano', 'Razas medianas'),
  ('breed-perro-basenji', 'species-perro', 'Basenji', 'Razas medianas'),
  ('breed-perro-chow-chow', 'species-perro', 'Chow Chow', 'Razas medianas'),
  ('breed-perro-dalmata', 'species-perro', 'Dálmata', 'Razas medianas'),
  ('breed-perro-brittany', 'species-perro', 'Brittany Spaniel', 'Razas medianas'),
  ('breed-perro-vizsla', 'species-perro', 'Vizsla', 'Razas medianas'),
  ('breed-perro-shiba-inu', 'species-perro', 'Shiba Inu', 'Razas medianas'),
  ('breed-perro-akita', 'species-perro', 'Akita Inu', 'Razas medianas'),
  ('breed-perro-amstaff', 'species-perro', 'American Staffordshire Terrier', 'Razas medianas'),
  ('breed-perro-pitbull', 'species-perro', 'Pitbull Terrier Americano', 'Razas medianas'),
  ('breed-perro-basset-hound', 'species-perro', 'Basset Hound', 'Razas medianas'),
  ('breed-perro-labrador', 'species-perro', 'Labrador Retriever', 'Razas grandes'),
  ('breed-perro-golden', 'species-perro', 'Golden Retriever', 'Razas grandes'),
  ('breed-perro-pastor-aleman', 'species-perro', 'Pastor Alemán', 'Razas grandes'),
  ('breed-perro-malinois', 'species-perro', 'Pastor Belga Malinois', 'Razas grandes'),
  ('breed-perro-groenendael', 'species-perro', 'Pastor Belga Groenendael', 'Razas grandes'),
  ('breed-perro-pastor-suizo', 'species-perro', 'Pastor Suizo', 'Razas grandes'),
  ('breed-perro-rottweiler', 'species-perro', 'Rottweiler', 'Razas grandes'),
  ('breed-perro-doberman', 'species-perro', 'Doberman', 'Razas grandes'),
  ('breed-perro-boxer', 'species-perro', 'Boxer', 'Razas grandes'),
  ('breed-perro-weimaraner', 'species-perro', 'Weimaraner', 'Razas grandes'),
  ('breed-perro-gran-danes', 'species-perro', 'Gran Danés', 'Razas grandes'),
  ('breed-perro-san-bernardo', 'species-perro', 'San Bernardo', 'Razas grandes'),
  ('breed-perro-terranova', 'species-perro', 'Terranova', 'Razas grandes'),
  ('breed-perro-bernes', 'species-perro', 'Bernés de la Montaña', 'Razas grandes'),
  ('breed-perro-cane-corso', 'species-perro', 'Cane Corso', 'Razas grandes'),
  ('breed-perro-dogo-argentino', 'species-perro', 'Dogo Argentino', 'Razas grandes'),
  ('breed-perro-fila', 'species-perro', 'Fila Brasileiro', 'Razas grandes'),
  ('breed-perro-mastin-napolitano', 'species-perro', 'Mastín Napolitano', 'Razas grandes'),
  ('breed-perro-mastin-ingles', 'species-perro', 'Mastín Inglés', 'Razas grandes'),
  ('breed-perro-mastin-espanol', 'species-perro', 'Mastín Español', 'Razas grandes'),
  ('breed-perro-leonberger', 'species-perro', 'Leonberger', 'Razas grandes'),
  ('breed-perro-rhodesian', 'species-perro', 'Rhodesian Ridgeback', 'Razas grandes'),
  ('breed-perro-malamute', 'species-perro', 'Alaskan Malamute', 'Razas grandes'),
  ('breed-perro-setter-irlandes', 'species-perro', 'Setter Irlandés', 'Razas grandes'),
  ('breed-perro-collie', 'species-perro', 'Collie', 'Razas grandes'),
  ('breed-perro-borzoi', 'species-perro', 'Borzoi', 'Razas grandes'),
  ('breed-perro-airedale', 'species-perro', 'Airedale Terrier', 'Razas grandes'),
  ('breed-perro-boyero-berna', 'species-perro', 'Boyero de Berna', 'Razas de trabajo / pastoreo'),
  ('breed-perro-pastor-anatolia', 'species-perro', 'Pastor de Anatolia', 'Razas de trabajo / pastoreo'),
  ('breed-perro-pastor-catalan', 'species-perro', 'Pastor Catalán', 'Razas de trabajo / pastoreo'),
  ('breed-perro-pastor-brie', 'species-perro', 'Pastor de Brie', 'Razas de trabajo / pastoreo'),
  ('breed-perro-komondor', 'species-perro', 'Komondor', 'Razas de trabajo / pastoreo'),
  ('breed-perro-pastor-maremmano', 'species-perro', 'Pastor Maremmano', 'Razas de trabajo / pastoreo'),
  ('breed-perro-old-english-sheepdog', 'species-perro', 'Old English Sheepdog', 'Razas de trabajo / pastoreo'),
  ('breed-perro-corgi-pembroke', 'species-perro', 'Corgi Pembroke', 'Razas de trabajo / pastoreo'),
  ('breed-perro-corgi-cardigan', 'species-perro', 'Corgi Cardigan', 'Razas de trabajo / pastoreo'),
  ('breed-perro-fox-terrier', 'species-perro', 'Fox Terrier', 'Razas tipo terrier'),
  ('breed-perro-bloodhound', 'species-perro', 'Bloodhound', 'Razas tipo sabueso / caza'),
  ('breed-perro-pointer-ingles', 'species-perro', 'Pointer Inglés', 'Razas tipo sabueso / caza'),
  ('breed-perro-coonhound', 'species-perro', 'Coonhound', 'Razas tipo sabueso / caza'),
  ('breed-perro-galgo-espanol', 'species-perro', 'Galgo Español', 'Razas tipo sabueso / caza'),
  ('breed-perro-greyhound', 'species-perro', 'Greyhound', 'Razas tipo sabueso / caza'),
  ('breed-perro-xoloitzcuintle', 'species-perro', 'Xoloitzcuintle', 'Razas menos comunes en Chile'),
  ('breed-perro-perro-sin-pelo', 'species-perro', 'Perro sin pelo del Perú', 'Razas menos comunes en Chile'),
  ('breed-perro-dogo-burdeos', 'species-perro', 'Dogo de Burdeos', 'Razas menos comunes en Chile'),
  ('breed-perro-keeshond', 'species-perro', 'Keeshond', 'Razas menos comunes en Chile'),
  ('breed-perro-schipperke', 'species-perro', 'Schipperke', 'Razas menos comunes en Chile'),
  ('breed-perro-saluki', 'species-perro', 'Saluki', 'Razas menos comunes en Chile'),
  ('breed-perro-boerboel', 'species-perro', 'Boerboel', 'Razas menos comunes en Chile'),
  ('breed-perro-tosa-inu', 'species-perro', 'Tosa Inu', 'Razas menos comunes en Chile'),
  ('breed-perro-kuvasz', 'species-perro', 'Kuvasz', 'Razas menos comunes en Chile'),
  ('breed-perro-flat-coated', 'species-perro', 'Flat Coated Retriever', 'Razas menos comunes en Chile'),
  ('breed-perro-nova-scotia', 'species-perro', 'Nova Scotia Duck Tolling Retriever', 'Razas menos comunes en Chile'),
  ('breed-perro-lobero-irlandes', 'species-perro', 'Lobero Irlandés', 'Razas gigantes');

-- Gatos
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-gato-mestizo', 'species-gato', 'Mestizo / Común Europeo', 'Comunes'),
  ('breed-gato-pelo-corto', 'species-gato', 'Doméstico de Pelo Corto', 'Comunes'),
  ('breed-gato-pelo-largo', 'species-gato', 'Doméstico de Pelo Largo', 'Comunes'),
  ('breed-gato-srd', 'species-gato', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-gato-otra', 'species-gato', 'Otra raza', 'Comunes'),
  ('breed-gato-no-identificada', 'species-gato', 'No identificada', 'Comunes'),
  ('breed-gato-en-evaluacion', 'species-gato', 'En evaluación', 'Comunes'),
  ('breed-gato-siames', 'species-gato', 'Siamés', 'Razas de pelo corto'),
  ('breed-gato-persa', 'species-gato', 'Persa', 'Razas de pelo largo'),
  ('breed-gato-maine-coon', 'species-gato', 'Maine Coon', 'Razas de pelo largo'),
  ('breed-gato-bengali', 'species-gato', 'Bengalí', 'Razas de pelo corto'),
  ('breed-gato-british-shorthair', 'species-gato', 'British Shorthair', 'Razas de pelo corto'),
  ('breed-gato-ragdoll', 'species-gato', 'Ragdoll', 'Razas de pelo largo'),
  ('breed-gato-sphynx', 'species-gato', 'Sphynx', 'Razas de pelo corto'),
  ('breed-gato-azul-ruso', 'species-gato', 'Azul Ruso', 'Razas de pelo corto'),
  ('breed-gato-angora-turco', 'species-gato', 'Angora Turco', 'Razas de pelo largo'),
  ('breed-gato-noruego-bosque', 'species-gato', 'Bosque de Noruega', 'Razas de pelo largo'),
  ('breed-gato-abisinio', 'species-gato', 'Abisinio', 'Razas de pelo corto'),
  ('breed-gato-scottish-fold', 'species-gato', 'Scottish Fold', 'Razas de pelo corto'),
  ('breed-gato-himalayo', 'species-gato', 'Himalayo', 'Razas de pelo largo'),
  ('breed-gato-burmes', 'species-gato', 'Burmés', 'Razas de pelo corto'),
  ('breed-gato-savannah', 'species-gato', 'Savannah', 'Razas de pelo corto'),
  ('breed-gato-devon-rex', 'species-gato', 'Devon Rex', 'Razas de pelo corto'),
  ('breed-gato-cornish-rex', 'species-gato', 'Cornish Rex', 'Razas de pelo corto'),
  ('breed-gato-otro', 'species-gato', 'Otro', 'Comunes');

-- Aves
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-ave-mestizo', 'species-ave', 'Mestizo', 'Comunes'),
  ('breed-ave-srd', 'species-ave', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-ave-otra', 'species-ave', 'Otra raza', 'Comunes'),
  ('breed-ave-no-identificada', 'species-ave', 'No identificada', 'Comunes'),
  ('breed-ave-periquito', 'species-ave', 'Periquito Australiano', 'Compañía'),
  ('breed-ave-ninfa', 'species-ave', 'Ninfa / Carolino', 'Compañía'),
  ('breed-ave-agapornis', 'species-ave', 'Agapornis', 'Compañía'),
  ('breed-ave-cotorra-argentina', 'species-ave', 'Cotorra Argentina', 'Compañía'),
  ('breed-ave-canario', 'species-ave', 'Canario', 'Compañía'),
  ('breed-ave-diamante-mandarin', 'species-ave', 'Diamante Mandarín', 'Compañía'),
  ('breed-ave-loro-amazona', 'species-ave', 'Loro Amazona', 'Compañía'),
  ('breed-ave-guacamayo', 'species-ave', 'Guacamayo', 'Compañía'),
  ('breed-ave-cacatua', 'species-ave', 'Cacatúa', 'Compañía'),
  ('breed-ave-eclectus', 'species-ave', 'Eclectus', 'Compañía'),
  ('breed-ave-yaco-africano', 'species-ave', 'Yaco Africano', 'Compañía'),
  ('breed-ave-caique', 'species-ave', 'Caique', 'Compañía'),
  ('breed-ave-conure', 'species-ave', 'Conure', 'Compañía'),
  ('breed-ave-tucan', 'species-ave', 'Tucán', 'Compañía'),
  ('breed-ave-gallina', 'species-ave', 'Gallina', 'Corral / Producción'),
  ('breed-ave-gallo', 'species-ave', 'Gallo', 'Corral / Producción'),
  ('breed-ave-pollo-broiler', 'species-ave', 'Pollo Broiler', 'Corral / Producción'),
  ('breed-ave-pato', 'species-ave', 'Pato', 'Corral / Producción'),
  ('breed-ave-ganso', 'species-ave', 'Ganso', 'Corral / Producción'),
  ('breed-ave-pavo', 'species-ave', 'Pavo', 'Corral / Producción'),
  ('breed-ave-codorniz', 'species-ave', 'Codorniz', 'Corral / Producción'),
  ('breed-ave-faisan', 'species-ave', 'Faisán', 'Ornamentales'),
  ('breed-ave-pavo-real', 'species-ave', 'Pavo Real', 'Ornamentales');

-- Reptiles
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-reptil-mestizo', 'species-reptil', 'Mestizo', 'Comunes'),
  ('breed-reptil-srd', 'species-reptil', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-reptil-otra', 'species-reptil', 'Otra raza', 'Comunes'),
  ('breed-reptil-no-identificada', 'species-reptil', 'No identificada', 'Comunes'),
  ('breed-reptil-iguana-verde', 'species-reptil', 'Iguana Verde', 'Reptiles'),
  ('breed-reptil-gecko-leopardo', 'species-reptil', 'Gecko Leopardo', 'Reptiles'),
  ('breed-reptil-gecko-crestado', 'species-reptil', 'Gecko Crestado', 'Reptiles'),
  ('breed-reptil-dragon-barbudo', 'species-reptil', 'Dragón Barbudo', 'Reptiles'),
  ('breed-reptil-camaleon', 'species-reptil', 'Camaleón', 'Reptiles'),
  ('breed-reptil-tortuga-tierra', 'species-reptil', 'Tortuga de Tierra', 'Reptiles'),
  ('breed-reptil-tortuga-agua', 'species-reptil', 'Tortuga de Agua', 'Reptiles'),
  ('breed-reptil-boa-constrictor', 'species-reptil', 'Boa Constrictor', 'Reptiles'),
  ('breed-reptil-piton-bola', 'species-reptil', 'Pitón Bola', 'Reptiles'),
  ('breed-reptil-serpiente-maiz', 'species-reptil', 'Serpiente del Maíz', 'Reptiles'),
  ('breed-reptil-anolis', 'species-reptil', 'Anolis', 'Reptiles'),
  ('breed-reptil-monitor', 'species-reptil', 'Monitor', 'Reptiles'),
  ('breed-reptil-skink', 'species-reptil', 'Skink', 'Reptiles'),
  ('breed-reptil-otro', 'species-reptil', 'Otro', 'Reptiles');

-- Roedores
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-roedor-mestizo', 'species-roedor', 'Mestizo', 'Comunes'),
  ('breed-roedor-srd', 'species-roedor', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-roedor-otra', 'species-roedor', 'Otra raza', 'Comunes'),
  ('breed-roedor-no-identificada', 'species-roedor', 'No identificada', 'Comunes'),
  ('breed-roedor-hamster-sirio', 'species-roedor', 'Hámster Sirio', 'Roedores'),
  ('breed-roedor-hamster-ruso', 'species-roedor', 'Hámster Ruso', 'Roedores'),
  ('breed-roedor-cobayo', 'species-roedor', 'Cobayo / Cuy / Cuyo', 'Roedores'),
  ('breed-roedor-raton', 'species-roedor', 'Ratón', 'Roedores'),
  ('breed-roedor-rata', 'species-roedor', 'Rata', 'Roedores'),
  ('breed-roedor-chinchilla', 'species-roedor', 'Chinchilla', 'Roedores'),
  ('breed-roedor-degu', 'species-roedor', 'Degú', 'Roedores'),
  ('breed-roedor-jerbo', 'species-roedor', 'Jerbo', 'Roedores'),
  ('breed-roedor-ardilla', 'species-roedor', 'Ardilla', 'Roedores'),
  ('breed-roedor-otro', 'species-roedor', 'Otro', 'Roedores');

-- Conejos y Lagomorfos
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-conejo-mestizo', 'species-conejo', 'Mestizo', 'Comunes'),
  ('breed-conejo-srd', 'species-conejo', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-conejo-otra', 'species-conejo', 'Otra raza', 'Comunes'),
  ('breed-conejo-no-identificada', 'species-conejo', 'No identificada', 'Comunes'),
  ('breed-conejo-cabeza-leon', 'species-conejo', 'Conejo Cabeza de León', 'Conejos'),
  ('breed-conejo-holland-lop', 'species-conejo', 'Holland Lop', 'Conejos'),
  ('breed-conejo-mini-lop', 'species-conejo', 'Mini Lop', 'Conejos'),
  ('breed-conejo-rex', 'species-conejo', 'Rex', 'Conejos'),
  ('breed-conejo-californiano', 'species-conejo', 'Californiano', 'Conejos'),
  ('breed-conejo-neozelandes', 'species-conejo', 'Neozelandés', 'Conejos'),
  ('breed-conejo-belier', 'species-conejo', 'Belier', 'Conejos'),
  ('breed-conejo-angora', 'species-conejo', 'Angora', 'Conejos'),
  ('breed-conejo-mini-rex', 'species-conejo', 'Mini Rex', 'Conejos'),
  ('breed-conejo-mestizo-b', 'species-conejo', 'Mestizo', 'Conejos'),
  ('breed-conejo-otro', 'species-conejo', 'Otro', 'Conejos');

-- Hurones
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-huron-mestizo', 'species-huron', 'Mestizo', 'Comunes'),
  ('breed-huron-srd', 'species-huron', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-huron-otra', 'species-huron', 'Otra raza', 'Comunes'),
  ('breed-huron-no-identificada', 'species-huron', 'No identificada', 'Comunes'),
  ('breed-huron-albino', 'species-huron', 'Hurón Albino', 'Hurones'),
  ('breed-huron-sable', 'species-huron', 'Hurón Sable', 'Hurones'),
  ('breed-huron-panda', 'species-huron', 'Hurón Panda', 'Hurones'),
  ('breed-huron-champagne', 'species-huron', 'Hurón Champagne', 'Hurones'),
  ('breed-huron-mestizo-b', 'species-huron', 'Mestizo', 'Hurones'),
  ('breed-huron-otro', 'species-huron', 'Otro', 'Hurones');

-- Animales de Granja
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-granja-mestizo', 'species-granja', 'Mestizo', 'Comunes'),
  ('breed-granja-srd', 'species-granja', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-granja-otra', 'species-granja', 'Otra raza', 'Comunes'),
  ('breed-granja-no-identificada', 'species-granja', 'No identificada', 'Comunes'),
  ('breed-granja-holstein', 'species-granja', 'Holstein', 'Bovinos'),
  ('breed-granja-jersey', 'species-granja', 'Jersey', 'Bovinos'),
  ('breed-granja-angus', 'species-granja', 'Angus', 'Bovinos'),
  ('breed-granja-hereford', 'species-granja', 'Hereford', 'Bovinos'),
  ('breed-granja-wagyu', 'species-granja', 'Wagyu', 'Bovinos'),
  ('breed-granja-overo-colorado', 'species-granja', 'Overo Colorado', 'Bovinos'),
  ('breed-granja-clavel-aleman', 'species-granja', 'Clavel Alemán', 'Bovinos'),
  ('breed-granja-suffolk', 'species-granja', 'Suffolk', 'Ovinos'),
  ('breed-granja-merino', 'species-granja', 'Merino', 'Ovinos'),
  ('breed-granja-dorset', 'species-granja', 'Dorset', 'Ovinos'),
  ('breed-granja-romney-marsh', 'species-granja', 'Romney Marsh', 'Ovinos'),
  ('breed-granja-boer', 'species-granja', 'Boer', 'Caprinos'),
  ('breed-granja-saanen', 'species-granja', 'Saanen', 'Caprinos'),
  ('breed-granja-anglo-nubian', 'species-granja', 'Anglo Nubian', 'Caprinos'),
  ('breed-granja-landrace', 'species-granja', 'Landrace', 'Porcinos'),
  ('breed-granja-yorkshire', 'species-granja', 'Yorkshire', 'Porcinos'),
  ('breed-granja-duroc', 'species-granja', 'Duroc', 'Porcinos'),
  ('breed-granja-pietrain', 'species-granja', 'Pietrain', 'Porcinos'),
  ('breed-granja-alpaca', 'species-granja', 'Alpaca', 'Camélidos'),
  ('breed-granja-llama', 'species-granja', 'Llama', 'Camélidos');

-- Equinos
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-equino-mestizo', 'species-equino', 'Mestizo', 'Comunes'),
  ('breed-equino-srd', 'species-equino', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-equino-otra', 'species-equino', 'Otra raza', 'Comunes'),
  ('breed-equino-no-identificada', 'species-equino', 'No identificada', 'Comunes'),
  ('breed-equino-criollo-chileno', 'species-equino', 'Criollo Chileno', 'Equinos'),
  ('breed-equino-cuarto-milla', 'species-equino', 'Cuarto de Milla', 'Equinos'),
  ('breed-equino-arabe', 'species-equino', 'Árabe', 'Equinos'),
  ('breed-equino-pura-sangre', 'species-equino', 'Pura Sangre Inglés', 'Equinos'),
  ('breed-equino-appaloosa', 'species-equino', 'Appaloosa', 'Equinos'),
  ('breed-equino-andaluz', 'species-equino', 'Andaluz', 'Equinos'),
  ('breed-equino-percheron', 'species-equino', 'Percherón', 'Equinos'),
  ('breed-equino-frison', 'species-equino', 'Frisón', 'Equinos'),
  ('breed-equino-mestizo-b', 'species-equino', 'Mestizo', 'Equinos'),
  ('breed-equino-pony', 'species-equino', 'Pony', 'Equinos'),
  ('breed-equino-otro', 'species-equino', 'Otro', 'Equinos');

-- Exóticos
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-exotico-mestizo', 'species-exotico', 'Mestizo', 'Comunes'),
  ('breed-exotico-srd', 'species-exotico', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-exotico-otra', 'species-exotico', 'Otra raza', 'Comunes'),
  ('breed-exotico-no-identificada', 'species-exotico', 'No identificada', 'Comunes'),
  ('breed-exotico-erizo-africano', 'species-exotico', 'Erizo Africano', 'Exóticos'),
  ('breed-exotico-sugar-glider', 'species-exotico', 'Sugar Glider', 'Exóticos'),
  ('breed-exotico-mono-titi', 'species-exotico', 'Mono Tití', 'Exóticos'),
  ('breed-exotico-zorrillo', 'species-exotico', 'Zorrillo doméstico', 'Exóticos'),
  ('breed-exotico-axolote', 'species-exotico', 'Axolote', 'Exóticos'),
  ('breed-exotico-tarantula', 'species-exotico', 'Tarántula', 'Exóticos'),
  ('breed-exotico-escorpion', 'species-exotico', 'Escorpión', 'Exóticos'),
  ('breed-exotico-rana-pacman', 'species-exotico', 'Rana Pacman', 'Exóticos'),
  ('breed-exotico-rana-arboricola', 'species-exotico', 'Rana Arborícola', 'Exóticos'),
  ('breed-exotico-caracol-gigante', 'species-exotico', 'Caracol Gigante Africano', 'Exóticos'),
  ('breed-exotico-otro', 'species-exotico', 'Otro', 'Exóticos');

-- Otro
INSERT OR IGNORE INTO breeds (id, species_group_id, name, breed_group) VALUES
  ('breed-otro-mestizo', 'species-otro', 'Mestizo', 'Comunes'),
  ('breed-otro-srd', 'species-otro', 'Sin raza definida (SRD)', 'Comunes'),
  ('breed-otro-otra', 'species-otro', 'Otra raza', 'Comunes'),
  ('breed-otro-no-identificada', 'species-otro', 'No identificada', 'Comunes');